CREATE TABLE IF NOT EXISTS urls (
  code VARCHAR(16) PRIMARY KEY,
  url TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  click_count INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE urls
  ADD COLUMN IF NOT EXISTS click_count INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS clicks (
  id SERIAL PRIMARY KEY,
  code TEXT NOT NULL REFERENCES urls(code) ON DELETE CASCADE,
  clicked_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS clicks_code_clicked_at_idx
  ON clicks (code, clicked_at DESC);
